definitions:
  model.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/books:
    get:
      description: Retrieve a list of all available books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
      summary: Get all books
      tags:
      - books
swagger: "2.0"
